### ISSUE TITLE
After update CMHW -> CMSDK...

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/android_vendor_resurrection#10]
I can not understand, what package are broken, but stopped working CMHW.
For example, here it (https://github.com/ShevT/device_samsung_lt033g/blob/cm-12.1/cmhw/org/cyanogenmod/hardware/KeyDisabler.java) stopped working on the current sources ResurrectionRemix, but continues to work in Cyanogenmod.

**Comment by varund7726** [comment]
because we track our own repo for cmhw 
and latest cmhw commits break build for RR so we reverted it
hence the issues

**Comment by ShevT** [comment]
In CyanogenMOD this update completely silently passed. How it cmhw works, and continue to work. They even did not have to change.
But here it stopped working. Apparently not all reverted.

You will work in this direction? Сmhw very necessary...

**Comment by varund7726** [comment]
It works now

**Comment by ShevT** [comment]
Yes. Thanks
