### ISSUE TITLE
ambiensdk

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/android_vendor_resurrection#23]
Hi guy.
CAn you update your vendor to add new feature of cm please ?? 
you need https://github.com/CyanogenMod/android_vendor_cm/commit/fd28e9d8193e246802a8357beeaa2230aebee419 for building now or it will break.
Thanks

**Comment by micky387** [comment]
thanks.I see you have added it.
I think you need to update too your android manifest -->readme for install new package MAVEN needed for futur build.
regards

**Comment by akhilnarang** [comment]
https://github.com/ResurrectionRemix/platform_manifest/commit/683dc12fbdae41b62692ad5a70131a4c1c32d45a
