### ISSUE TITLE
bootanimation

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/android_vendor_resurrection#24]
Hi,
Can you add new resolution for my samsung galaxy note edge please ??
it's a note 4 but with 1600 x 2560 (note 4 are 1440 x 2560)
If i choose 1600 in TARGET_SCREEN_WIDTH,it dont choose the good res.
I suggest you can add 1600_E.zip or other in your common/bootanimation .
What do you think ??
regards

**Comment by regalstreak** [comment]
Why not make one and submit a pull req?

**Comment by micky387** [comment]
yes,of course,i can.
