### ISSUE TITLE
Couple of request / Issues noticed

### ISSUE THREAD

**Issue by Santhoshsurya** [ResurrectionRemix/android_vendor_resurrection#26]
Hi,
I'm loving your job. Keep up the good work.

 - please give option to reduce navbar size beyond 65%, it looks way more bigger than I require and eats up extra screen space, please give back the ability to add additional buttons to navbar as it was before. Dim option of navebar is also missing in latest version of CM13.

 - I'm not able to install Google camera (v2.7) nor (3.1) in latest version of CM13. I get error as "unfortunately, camera has stopped". Stock camera works fine.

 - If I'm on a call and the screen gets locked and call is disconnected, call screen appears for fraction of second on unlocking the screen.

**Comment by varund7726** [comment]
1. Read detailed changelog .we have a whole new navbar implementation
2.that's your device specific issue contact ur maintainer
3.same as point 2 because I have no such issues

**Comment by Santhoshsurya** [comment]
Thanks for the reply dude, I'll see wat I can do. Good Day.

**Comment by akhilnarang** [comment]
You still can add more buttons.......
