### ISSUE TITLE
No network data

### ISSUE THREAD

**Issue by zvrkan5** [ResurrectionRemix/android_vendor_resurrection#27]
Hi there,

I have a Note3 and just upgraded to your latest build 5.6.5 -20160312-hlte
But since the upgrade i have lost network data. I can make calls but i cannot get network data to work.
Tried 3G, tried LTE - but nothing works.

Wondering if this could be a simple quick fix?

**Comment by darkman1983** [comment]
For me going to flightmode or restarting the phone helped.
But I'm on Note 4 😀

**Comment by varund7726** [comment]
This is a device specific cm issue....no use reporting it here
must report on cm13 thread
