### ISSUE TITLE
 without mobile data ResurrectionRemix - v5.6.8 - Android r30 - 20160502

### ISSUE THREAD

**Issue by tassiosilva1** [ResurrectionRemix/android_vendor_resurrection#31]
good night , do not speak English, I have a problem after installing the rom ResurrectionRemix - v5.6.8 - Android r30 - 20160502 , can not get access to mobile data 3g and 2g , have no access to mobile network, thanks

**Comment by varund7726** [comment]
Mention your device  ,build date , and post in the g+ community in the correct section
https://plus.google.com/communities/109352646351468373340
