### ISSUE TITLE
Call Screen Delay

### ISSUE THREAD

**Issue by Santhoshsurya** [ResurrectionRemix/android_vendor_resurrection#34]
Hello,
Hope you are doing well.

From past couple of updates I'm facing call screen delay issue, earlier things were fine.

**Description:**
When I receive any incoming call, phone starts ringing/vibrating but the screen takes 2-5 seconds to light-up and display. Please look into the issue, or do let me know of any possible fixes.
I have done a clean installation and checked instantly but the issue still persists. I'm using Note2 with latest release of RR Marshmallow.

Thanks,
Santhosh

**Comment by varund7726** [comment]
thats your device specific problem in cm source...not the problem of RR
good day!
