### ISSUE TITLE
lock screen message setting invisible on dark design

### ISSUE THREAD

**Issue by flippinger** [ResurrectionRemix/android_vendor_resurrection#40]
When you set "Display & LEDs -> Design" to "Dark", the text field of "Security -> Lock screen message" is white text on white background.

![image](https://cloud.githubusercontent.com/assets/3148313/19023018/9b20f3b4-88e4-11e6-929e-8d6b684f0231.png)

**Comment by varund7726** [comment]
Aosp issue
