### ISSUE TITLE
unable to acces to the callforward menu

### ISSUE THREAD

**Issue by pippo73** [ResurrectionRemix/android_vendor_resurrection#49]
Hi all, 
I've just intalled this rom on my Xiaomi Kenzo, but i cannot find the callforward settings.
If I use the IMI codes , it works, but there is no way to reach the menu that was in "phone app = menu = settings = call forward"

how to enable it?

thank you

**Comment by pippo73** [comment]
May I know it was closed without any feedback?

**Comment by varund7726** [comment]
Because this is not the correct place to ask .
Please ask on the g+ community so other users with your device can help you .
Thanks
