### ISSUE TITLE
New way to build tutorial is may incomplete

### ISSUE THREAD

**Issue by Herny64** [ResurrectionRemix/android_vendor_resurrection#68]
Hi,
When im trying to do the "New way to set up and build Resurrection Remix" im stuck at "Once done, the source code should be already set up ".
I do not have the source code on my machine at this stage of the tutorial.
In the scripts repository from akhilnarang are only scripts to download dependencies and i cant find a "build.sh".

**Comment by akhilnarang** [comment]
Github.com/resurrectionremix/resurrectedscripts

**Comment by Herny64** [comment]
thank you, the scripts are only for marshmallow, what is the proper way to build nougat ?

**Comment by akhilnarang** [comment]
Scripts are not maintained any more
If you wish to use them you'll have to adapt on your own
