### ISSUE TITLE
Camera and GPS problems on Redmi Note 3 Special Edition (kate)

### ISSUE THREAD

**Issue by Poomex** [ResurrectionRemix/android_vendor_resurrection#69]
I installed RR-N-v5.8.0-20170114-kenzo-Nightly.zip on my kate. I also have microG installed. Everything works great except for two things:
- The camera is extremely grainy and low resolution. The phone has a 13 MP camera but the image looks like 5 MP tops. Additionally, the camera has terrible stuttering issues when moving. The same thing happens with recording video. 
I have tried installing alternative camera apps from F-droid, but the problem persists. 
- GPS works very badly, it detects a few satellites at most and there seems to be no support for GLONASS and a few other navigation systems. Only GPS satellites are displayed in SatStat

**Comment by akhilnarang** [comment]
Works fine on kenzo
Build is made for kenzo not for Kate, sorry can't help

**Comment by varund7726** [comment]
please avoid reporting issues on github. you will get more support on g+
