### ISSUE TITLE
Fingerprint sensor dont wake-up screen

### ISSUE THREAD

**Issue by alyssonwentz** [ResurrectionRemix/android_vendor_resurrection#70]
I instaled the v5.8.1 and when i touch the sensor, dont wakeu-p the screen. To unlock i need to wake-up screen with the unlock side button and then touch the sensor. Do i did something wrong? Sometimes it works with the screen off. Clean install from freedom ROM

**Comment by akhilnarang** [comment]
Don't report here. Report to your maintainer on XDA or G+. Mention the device.
