### ISSUE TITLE
Revert "Disable SU by default"

### ISSUE THREAD

**Issue by DX37** [ResurrectionRemix/android_vendor_resurrection#81]
You got disabled SU by default. [Again](https://github.com/ResurrectionRemix/android_vendor_resurrection/commit/2f3808e416d54b052d5f734995019c4eebbfba04).

**Comment by varund7726** [comment]
Seriously? You didn't see that we have magisk?

**Comment by DX37** [comment]
Oh, a new feature. Then why the hell it request SU permissions for work?
Without su binary, it will never work.

**Comment by varund7726** [comment]
What are you saying man? Magisk takes care of the root issues .we have magisk apk and zip that patches superuser stuff 
Magisk has inbuilt su and it works .
What your saying it will never work lol . we've been using it without issues

**Comment by DX37** [comment]
One question - is SU permissions will activates out of box, or user need to go to Magisk and do some stuff to activate it?

**Comment by varund7726** [comment]
RR is rooted out of the box . to handle root permissions he needs to go to magisk app 
The advantage of magisk app is it bypasses safetynet protection and allows user to use apps like android pay

**Comment by DX37** [comment]
Okay. I realized wtf is going on. According to [this](https://github.com/ResurrectionRemix/android_build/commit/bd62fbab559d7150c85d2bf544afb827c0af8e82#diff-7d8b45b07034fa692272eb5816bad9c3R826), Magisk will flashes if I building block based archive, right?

Well, I didn't use block based building. I take my words back.

**Comment by DX37** [comment]
@varund7726 I don't like this. Why you didn't using default Lineage's SU abilities? It always presents after wiping. Magisk always requires to flash it `magisk.zip` after /data wiping for getting root permissions.
What's the point of using permission manager, which have a few amount of modules with Xposed (without 7.1.1 support, btw. And a lot of Xposed modules require stock ROMs), and doesn't have PIN-code ability, like SuperSU?

**Comment by DX37** [comment]
And, seems like, SuperSU has a built-in recovery capability after the OTA-update.

**Comment by Timmmmaaahh** [comment]
DX37, can you please address this in the appropriate forum/g+ section? This is not a discussion platform.

**Comment by varund7726** [comment]
@DX37 many users want to use apps like android pay , Banking apps, Snapchat etc and other apps that require root check. Magisk bypasses it. it works fine on most devices . If it doesnt work on your device, Just revert the commits and build .its not so hard. 
and to answer your question , NO most devices don't require flashing magisk.zip
Its must be your device model (dunno what your building for )

We have to keep it because all apps are slowly going rootless.
if you dont like it , thats not our problem, just revert it

**Comment by DX37** [comment]
Ok, I'll post issue on forum...
