### ISSUE TITLE
Sepolicy Build errors

### ISSUE THREAD

**Issue by somadsul** [ResurrectionRemix/android_vendor_resurrection#82]
can you please revert your last commit in sysinit.te

getting following errors while building

[ 29% 9102/30610] build /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy
FAILED: /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy 
/bin/bash -c "(/home/som/RR_N/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/som/RR_N/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/som/RR_N/out/host/linux-x86/bin/sepolicy-analyze /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 	echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 	fi ) && (mv /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy )"
vendor/cm/sepolicy/sysinit.te:26:ERROR 'unknown type persist_file' at token ';' on line 22074:
allow sysinit persist_file:dir getattr;
allow sysinit cache_file:dir getattr;
checkpolicy:  error(s) encountered while parsing configuration
/home/som/RR_N/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/policy.conf
[ 29% 9102/30610] host C: sefcontext_compile <= external/libselinux/utils/sefcontext_compile.c

Got one more error

FAILED: /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy 
/bin/bash -c "(/home/som/RR_N/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/policy.conf ) && (/home/som/RR_N/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/home/som/RR_N/out/host/linux-x86/bin/sepolicy-analyze /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 	echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 	fi ) && (mv /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/som/RR_N/out/target/product/k3gxx/obj/ETC/sepolicy_intermediates/sepolicy )"
vendor/cm/sepolicy/system_server.te:19:ERROR 'unknown type persist_file' at token ';' on line 22109:
allow system_server persist_file:dir search;

checkpolicy:  error(s) encountered while parsing configuration

**Comment by varund7726** [comment]
If we do, substratum won't work .you'll have to fix in device tree 
Thanks

**Comment by westcripp** [comment]
@somadsul ok error fixed try to build
