### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by villarleg** [ResurrectionRemix/android_vendor_resurrection#83]
Since 3 days ago i have a bootloop, with the same device trees and kernel, no erros in build process,
In marshmallow branch
Logcat shows this error on boot process:

01-21 01:18:03.281   680   810 E slim_daemon: [NDK] bindNDKSensors: Sensor server is unavailable.

After 15 min of bootloop, there is no root and no kernel adiutor installed and i have it in vendor/cm/prebuilt/kerneladiutor

Building aokp i havnt got erros, and works su and kernel adiutor, no bootloop also, with same device trees and kernel trees, thanks for your awesome work!

**Comment by varund7726** [comment]
Can you give us more info on device ? And please take this to g+ .not here .thanks
